"""empty message

Revision ID: 0a4dee8658ea
Revises: 
Create Date: 2021-08-25 01:50:52.620273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a4dee8658ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_directories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quiz_directory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_directory_id'], ['quiz_directories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('card_number', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=1000), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quiz_template_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_template_id'], ['quiz_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('active_recall_utilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quiz_card_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_card_id'], ['quiz_cards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_active_recall_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_active_answer', sa.Text(), nullable=True),
    sa.Column('user_previous_answer', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quiz_card_id', sa.Integer(), nullable=False),
    sa.Column('active_recall_utility_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['active_recall_utility_id'], ['active_recall_utilities.id'], ),
    sa.ForeignKeyConstraint(['quiz_card_id'], ['quiz_cards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_active_recall_answers')
    op.drop_table('active_recall_utilities')
    op.drop_table('quiz_cards')
    op.drop_table('quiz_templates')
    op.drop_table('quiz_directories')
    op.drop_table('workspaces')
    op.drop_table('users')
    # ### end Alembic commands ###
