"""empty message

Revision ID: 1307f911b477
Revises: 44ff61aa24f0
Create Date: 2021-08-30 21:31:19.466186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1307f911b477'
down_revision = '44ff61aa24f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('active_recall_utilities', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('active_recall_utilities', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('quiz_cards', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('quiz_cards', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('quiz_directories', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('quiz_directories', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('quiz_templates', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('quiz_templates', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('workspaces', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('workspaces', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'updated_at')
    op.drop_column('workspaces', 'created_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('quiz_templates', 'updated_at')
    op.drop_column('quiz_templates', 'created_at')
    op.drop_column('quiz_directories', 'updated_at')
    op.drop_column('quiz_directories', 'created_at')
    op.drop_column('quiz_cards', 'updated_at')
    op.drop_column('quiz_cards', 'created_at')
    op.drop_column('active_recall_utilities', 'updated_at')
    op.drop_column('active_recall_utilities', 'created_at')
    # ### end Alembic commands ###
